# version 0.2

# Google Chrome 69.0.3497.92

FROM ratneshraval/cals-base:0.8

RUN apt-get install -y \
    chrpath \
    libssl-dev \
    bzip2 

RUN apt-get update -y
RUN apt-get upgrade -y

# install chrome binary
RUN wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list

RUN apt-get update && apt-get install --no-install-recommends -y google-chrome-stable

RUN export CHROME_BIN=/usr/bin/google-chrome
