engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    config:
      languages:
       - javascript
       - ruby
    enabled: true
  eslint:
    config:
      extensions:
        - .js
        - .jsx
    enabled: true
  fixme:
    checks:
      TODO:
        enabled: false
    enabled: true
  rubocop:
    enabled: true
exclude_paths:
  - config/
  - spec/
  - test/
  - vendor/
  - public/
  - docker/
  - coverage/
  - node_modules/
  - lib/
ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.haml"
    - "**.rb"
    - "**.rhtml"
    - "**.slim"
    - "**.inc"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
