version: "2"
checks:
  similar-code:
    enabled: false
plugins:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      extensions:
        - .js
        - .jsx
  fixme:
    checks:
      TODO:
        enabled: false
    enabled: true
  rubocop:
    enabled: true
exclude_patterns:
  - config/
  - spec/
  - test/
  - vendor/
  - public/
  - docker/
  - coverage/
  - node_modules/
  - lib/
