FROM ruby:latest

RUN gem install rails

RUN gem install puma

RUN apt-get update

# Get latest nodejs PPA
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -

# install nodejs and npm
RUN apt-get install -y nodejs

# get latest yarn repo
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# install yarn
RUN apt-get update && apt-get install yarn

RUN mkdir /var/www; cd /var/www;

# clone CALS
RUN git clone -b aws_dev https://github.com/ca-cwds/CALS.git /var/www/cals

WORKDIR /var/www/cals
RUN cd /var/www/cals

RUN bundle install

#run node package installer
RUN yarn install

# compile assets
RUN rails assets:precompile

#### ENV variables

# cals api url
ENV BASE_CALS_API_URL=http://calsmockapi:3001/v1
# cals redis host
ENV REDIS_SERVER_HOST=calsredis

# run rails server
# CMD rails server -e aws_dev -b 192.168.213.100
CMD rails server -e aws_dev -b 0.0.0.0


