FROM ratneshraval/cals-base:0.2

RUN mkdir /var/www \
  && cd /var/www

# clone CALS
RUN git clone -b development https://github.com/ca-cwds/CALS.git /var/www/cals

WORKDIR /var/www/cals

RUN cd /var/www/cals \
  && bundle install \
  && yarn install

# ENV variables
ENV BASE_CALS_API_URL=http://localhost:3001/v1 \
  CALS_API_URL=https://cals-api.preint.cwds.io \
  GEO_SERVICE_URL=https://geo.preint.cwds.io \
  CHROME=true


# RUN tests
RUN rails assets:precompile RAILS_ENV=test
RUN npm run spec-ci
RUN npm run karma-ci

# ENV variables
ENV BASE_CALS_API_URL=http://calsmockapi:3001/v1 \
  AUTHENTICATION_API_BASE_URL=http://perry.dev.cwds.tabordasolutions.net \
  REDIS_HOST=calsredis \
  REDIS_PORT=6379 \
  RAILS_RELATIVE_URL_ROOT=/cals

# compile assets
RUN rails assets:precompile RAILS_ENV=development

# run rails server
CMD rails server -e development -b 0.0.0.0 -p 3000
