const CountyList = Object.freeze({
    '01' : 'Alameda',
    '02' : 'Alpine',
    '03' : 'Amador',
    '04' : 'Butte',
    '05' : 'Calaveras',
    '06' : 'Colusa',
    '07' : 'Contra Costa',
    '08' : 'Del Norte',
    '09' : 'El Dorado',
    '10' : 'Fresno',
    '11' : 'Glenn',
    '12' : 'Humboldt',
    '13' : 'Imperial',
    '14' : 'Inyo',
    '15' : 'Kern',
    '16' : 'Kings',
    '17' : 'Lake',
    '18' : 'Lassen',
    '19' : 'Los Angeles',
    '20' : 'Madera',
    '21' : 'Marin',
    '22' : 'Mariposa',
    '23' : 'Mendocino',
    '24' : 'Merced',
    '25' : 'Modoc',
    '26' : 'Mono',
    '27' : 'Monterey',
    '28' : 'Napa',
    '29' : 'Nevada',
    '30' : 'Orange',
    '31' : 'Placer',
    '32' : 'Plumas',
    '33' : 'Riverside',
    '34' : 'Sacramento',
    '35' : 'San Benito',
    '36' : 'San Bernardino',
    '37' : 'San Diego',
    '38' : 'San Francisco',
    '39' : 'San Joaquin',
    '40' : 'San Luis Obispo',
    '41' : 'San Mateo',
    '42' : 'Santa Barbara',
    '43' : 'Santa Clara',
    '44' : 'Santa Cruz',
    '45' : 'Shasta',
    '46' : 'Sierra',
    '47' : 'Siskiyou',
    '48' : 'Solano',
    '49' : 'Sonoma',
    '50' : 'Stanislaus',
    '51' : 'Sutter',
    '52' : 'Tehama',
    '53' : 'Trinity',
    '54' : 'Tulare',
    '55' : 'Tuolumne',
    '56' : 'Ventura',
    '57' : 'Yolo',
    '58' : 'Yuba',
    '60' : 'OUT OF STATE'
});

const FacilityTypes = Object.freeze({
    '400' :  'ADOPTION AGENCY',
    '403' :  'RESOURCE FAMILY HOME',
    '430' :  'FOSTER FAMILY AGENCY',
    '431' : 'FOSTER FAMILY AGENCY SUB-',
    '432' :  'SUBSTITUTE EMPLOYMENT REGISTRY',
    '433' : 'FFA CERTIFIED HOME',
    '710' :  'SMALL FAMILY HOME',
    '711' : 'FOSTER FAMILY HOME',
    '720' : 'CRISIS NURSERY',
    '721' :  'TEMPORARY SHELTER CARE FACILITY',
    '722' :  'TRANSITIONAL SHELTER CARE FACILITY',
    '724' :   'TRANSITIONAL SHELTER CARE FACILITY FOR CHILDREN',
    '726' :   'TRANSITIONAL HOUSING PLACEMENT PROGRAM',
    '728' :  'COMMUNITY TREATMENT FACILITY',
    '729' :  'ENHANCED BEHAVIORAL SUPPORT HOME - GH',
    '730' :  'GROUP HOME',
    '731' :  'OUT OF STATE GROUP HOME',
    '732' :  'RUNAWAY AND HOMELESS YOUTH SHELTER - GH',
    '733' :  'SHORT TERM RESIDENTIAL THERAPEUTIC PROGRAM - GH'
});

export {CountyList, FacilityTypes};