
CALS_API_BASE_URL = ENV['BASE_CALS_API_URL']

AUTHENTICATION_API_BASE_URL = ENV['AUTHENTICATION_API_BASE_URL']

SANDBOX_LANDING_URL = ENV['SANDBOX_LANDING_URL']

# Redis server
REDIS_HOST = ENV['REDIS_HOST']
REDIS_PORT = ENV['REDIS_PORT']


#API_KEY = ENV['API_KEY']

# subdirectory deploy
RAILS_RELATIVE_URL_ROOT = ENV['RAILS_RELATIVE_URL_ROOT'] ? ENV['RAILS_RELATIVE_URL_ROOT'] : ''
