CALS_API_BASE_URL = ENV['BASE_CALS_API_URL']
CALS_API_URL = ENV['CALS_API_URL']
GEO_SERVICE_URL = ENV['GEO_SERVICE_URL']
AUTHENTICATION_API_BASE_URL = ENV['AUTHENTICATION_API_BASE_URL']
BASE_SEARCH_API_URL = ENV['BASE_SEARCH_API_URL']

SANDBOX_LANDING_URL = ENV['SANDBOX_LANDING_URL']

# Redis server
REDIS_HOST = ENV['REDIS_HOST']
REDIS_PORT = ENV['REDIS_PORT']

# subdirectory deploy
RAILS_RELATIVE_URL_ROOT = ENV['RAILS_RELATIVE_URL_ROOT'] ? ENV['RAILS_RELATIVE_URL_ROOT'] : ''
