CREATE TABLE CBC_ADDRESS (
    ISN_CBC_ADDRESS   INT       NOT NULL,
    ADR_PER_ID        CHAR (10) NULL,
    ADR_ADDRESS_TYPE  INT       NULL,
    ADR_ADDRESS1      CHAR (50) NULL,
    ADR_ADDRESS2      CHAR (50) NULL,
    ADR_APT_SUITE_NBR CHAR (20) NULL,
    ADR_CITY          CHAR (25) NULL,
    ADR_STATE         CHAR (2)  NULL,
    ADR_ZIP           INT       NULL,
    ADR_PLUS4         INT       NULL,
    ADR_COUNTY_ID     INT       NULL
);

CREATE TABLE CBC_APPLICANT (
    ISN_CBC_APPLICANT       INT        NOT NULL,
    APP_PER_ID              CHAR (10)  NOT NULL,
    APP_TLR_ID              CHAR (7)   NULL,
    APP_APPLICANT_TYPE      CHAR (1)   NULL,
    APP_PER_STATUS          CHAR (1)   NULL,
    APP_PER_STATUS_LUD      DATE       NULL,
    APP_STATUS_CRCS_OVERALL INT        NULL,
    APP_STATUS_CRCS_LUD     DATE       NULL,
    APP_UNEMPLOY_DATE       DATE       NULL,
    APP_CII_NBR             CHAR (20)  NULL,
    APP_FBI_NBR             CHAR (20)  NULL,
    APP_EXEMPT_CONDITIONS   CHAR (200) NULL,
    APP_ATI_NBR             CHAR (10)  NULL,
    APP_LIC508              CHAR (1)   NULL,
    APP_SIMPLIFIED          CHAR (1)   NULL,
    APP_EXEMPT_ANALYST_NBR  INT        NULL,
    APP_BIRS_ANALYST_NBR    INT        NULL,
    APP_DOJ_NLI             CHAR (1)   NULL,
    APP_CREATE_DATE         DATE       NULL,
    APP_CREATE_USER_ID      INT        NULL,
    APP_DEACTIVATE_DATE     DATE       NULL,
    APP_DEACTIVATE_USER_ID  INT        NULL,
    APP_ARCHIVE_DATE        DATE       NULL,
    APP_ARCHIVE_USER_ID     INT        NULL,
    APP_LAST_UPD_DATE       DATE       NULL,
    APP_LAST_UPD_USER_ID    INT        NULL,
    APP_TRANS_FROM          CHAR (1)   NULL,
    APP_RECEIVED_DATE       DATE       NULL,
    APP_ENTERED_DATE        DATE       NULL,
    APP_LUD_TIME            INT        NULL,
    APP_NAME_LUD_TIME       INT        NULL,
    APP_ADDR_LUD_TIME       INT        NULL,
    APP_CMT_LUD_TIME        INT        NULL,
    APP_CNT_LUD_TIME        INT        NULL,
    APP_DOB_LUD_TIME        INT        NULL,
    APP_SSN_LUD_TIME        INT        NULL,
    APP_ID_LUD_TIME         INT        NULL,
    APP_VS_LUD_TIME         INT        NULL,
    APP_ACTION_STATUS       INT        NULL,
    APP_PROCESS_USER        INT        NULL,
    APP_SLMS_RESP_DATE      DATE       NULL,
    APP_SLMS_DECSN_DATE     DATE       NULL,
    APP_DOJ_NOTIFY_DATE     DATE       NULL,
    APP_CRCS_CA             INT        NULL,
    APP_CRCS_DOJ            INT        NULL,
    APP_CRCS_FBI            INT        NULL,
    APP_PRIM_DOB            DATE       NULL,
    APP_PRIM_SSN            INT        NULL,
    APP_SEX                 CHAR (1)   NULL,
    APP_HEIGHT              INT        NULL,
    APP_WEIGHT              INT        NULL,
    APP_CITIZEN             CHAR (1)   NULL,
    APP_HAIR_COLOR          CHAR (10)  NULL,
    APP_EYE_COLOR           CHAR (10)  NULL,
    APP_STEP_STATUS_CA      INT        NULL,
    APP_STEP_STATUS_DOJ     INT        NULL,
    APP_STEP_STATUS_FBI     INT        NULL,
    APP_INDIVIDUAL          CHAR (1)   NULL,
    APP_CLEAR_LTR           CHAR (1)   NULL,
    APP_AA_FLAG             CHAR (1)   NULL,
    APP_PEND_LIC508D_FLAG   CHAR (1)   NULL,
    APP_PEND_LIC508D_DATE   DATE       NULL,
    APP_LIC508D_FLAG        CHAR (1)   NULL
);

CREATE TABLE CBC_BATCH_COUNT (
    ISN_CBC_BATCH_COUNT INT        NOT NULL,
    BT_REC_TYPE         CHAR (2)   NULL,
    BT_TRANS_DATE       DATE       NULL,
    BT_ANALYST_NBR      INT        NULL,
    BT_DATA_1           CHAR (250) NULL
);

CREATE TABLE CBC_CCLD_AGENCY (
    ISN_CBC_CCLD_AGENCY INT       NOT NULL,
    AGY_ID              CHAR (6)  NOT NULL,
    AGY_NBR             CHAR (15) NULL,
    AGY_TYPE            CHAR (5)  NULL,
    AGY_NAME            CHAR (30) NULL,
    AGY_ADDRESS1        CHAR (25) NULL,
    AGY_ADDRESS2        CHAR (25) NULL,
    AGY_CITY            CHAR (25) NULL,
    AGY_STATE           CHAR (2)  NULL,
    AGY_ZIP             CHAR (5)  NULL,
    AGY_PHONE           CHAR (15) NULL,
    AGY_FAX             CHAR (15) NULL,
    AGY_CONTACT         CHAR (30) NULL
);

CREATE TABLE CBC_COMMENT (
    ISN_CBC_COMMENT    INT        NOT NULL,
    CMT_PER_ID         CHAR (10)  NULL,
    CMT_CREATE_DATE    DATE       NULL,
    CMT_CREATE_USER_ID INT        NULL,
    CMT_COMMENT_DATE   DATE       NULL,
    CMT_COMMENT_1      CHAR (200) NULL,
    CMT_COMMENT_2      CHAR (200) NULL
);

CREATE TABLE CBC_CONTACT_INFO (
    ISN_CBC_CONTACT_INFO INT       NOT NULL,
    CNT_PER_ID           CHAR (10) NULL,
    CNT_CONTACT_TYPE     INT       NULL,
    CNT_CONTACT_DATA     CHAR (50) NULL,
    CNT_CREATE_DATE      DATE      NULL,
    CNT_CREATE_USER_ID   INT       NULL
);

CREATE TABLE CBC_DOB (
    ISN_CBC_DOB    INT       NOT NULL,
    DOB_PER_ID     CHAR (10) NULL,
    DOB_PRIMARY    CHAR (1)  NULL,
    DOB_BIRTH_DATE DATE      NULL,
    DOB_PER_STATUS CHAR (1)  NULL
);

CREATE TABLE CBC_HCA_APPL (
    HCA_PER_ID              VARCHAR (10) NULL,
    HCA_FIRST_REGISTRY_DATE DATE         NULL,
    HCA_REGISTRY_DATE       DATE         NULL,
    HCA_REGISTRY_STATUS     SMALLINT     NULL,
    HCA_PAYMENT_DATE        DATE         NULL,
    HCA_LAST_UPD_DATE       DATE         NULL,
    HCA_CLEAR_LTR           CHAR (1)     NULL,
    HCA_LAST_UPD_USER_ID    SMALLINT     NULL,
    HCA_CREATE_DATE         DATE         NULL,
    HCA_CREATE_USER_ID      SMALLINT     NULL,
    HCA_ISN                 INT          NULL
);

CREATE TABLE CBC_IDENT (
    ISN_CBC_IDENT INT       NOT NULL,
    ID_PER_ID     CHAR (10) NULL,
    ID_PRIMARY    CHAR (1)  NULL,
    ID_NBR        CHAR (20) NULL,
    ID_STATE      CHAR (3)  NULL,
    ID_PER_STATUS CHAR (1)  NULL
);

CREATE TABLE CBC_IHSS_APPL (
    ISN_CBC_IHSS_APPL        INT       NOT NULL,
    IHSS_PER_ID              CHAR (10) NULL,
    IHSS_CRCS                INT       NULL,
    IHSS_CLEARED_DATE        DATE      NULL,
    IHSS_CLOSED_DATE         DATE      NULL,
    IHSS_STEP_STATUS_DOJ     INT       NULL,
    IHSS_REC_DATE            DATE      NULL,
    IHSS_SOC_DENIAL_DATE     DATE      NULL,
    IHSS_SOC_EXCEPT_REC_DATE DATE      NULL,
    IHSS_CREATE_DATE         DATE      NULL,
    IHSS_CREATE_USER_ID      INT       NULL,
    IHSS_LAST_UPD_DATE       DATE      NULL,
    IHSS_LAST_UPD_USER_ID    INT       NULL
);

CREATE TABLE CBC_NAME (
    ISN_CBC_NAME   INT       NOT NULL,
    NM_PER_ID      CHAR (10) NULL,
    NM_NAME_TYPE   INT       NULL,
    NM_FIRST_NAME  CHAR (25) NULL,
    NM_MIDDLE_NAME CHAR (25) NULL,
    NM_LAST_NAME   CHAR (25) NULL,
    NM_SUFFIX      CHAR (5)  NULL,
    NM_PER_STATUS  CHAR (1)  NULL
);

CREATE TABLE CBC_PROCESS_BIRS (
    ISN_CBC_PROCESS_BIRS      INT       NOT NULL,
    BIRS_PER_ID               CHAR (10) NULL,
    BIRS_ANALYST_NBR          INT       NULL,
    BIRS_PRIORITY             CHAR (1)  NULL,
    BIRS_REFER_DATE           DATE      NULL,
    BIRS_INVESTIGATING_OFFICE INT       NULL,
    BIRS_STEP_DATE            DATE      NULL,
    BIRS_CREATE_DATE          DATE      NULL,
    BIRS_LAST_UPD_USER_ID     INT       NULL,
    BIRS_LAST_UPD_DATE        DATE      NULL,
    BIRS_LIC_TLR              CHAR (1)  NULL,
    BIRS_TAB_NBR              CHAR (2)  NULL,
    BIRS_DUP                  CHAR (1)  NULL,
    BIRS_RESOLVED_DATE_LIC    DATE      NULL,
    BIRS_RESOLVED_DATE_TLR    DATE      NULL
);

CREATE TABLE CBC_PROCESS_DOR (
    ISN_CBC_PROCESS_DOR INT        NOT NULL,
    DOR_PER_ID          CHAR (10)  NULL,
    DOR_ID              INT        NULL,
    DOR_NBR             CHAR (20)  NULL,
    DOR_EFFECTIVE_DATE  DATE       NULL,
    DOR_OPTION          INT        NULL,
    DOR_USER_ID         INT        NULL,
    DOR_CREATE_DATE     DATE       NULL,
    DOR_COMMENT         CHAR (100) NULL,
    DOR_SESSION_ID      INT        NULL
);

CREATE TABLE CBC_PROCESS_IND (
    ISN_CBC_PROCESS_IND INT       NOT NULL,
    IND_PER_ID          CHAR (10) NULL,
    IND_LIC_TLR         CHAR (1)  NULL,
    IND_TAB_NBR         CHAR (2)  NULL,
    IND_STEP_SEQ_NBR    INT       NULL,
    IND_STEP_CRCS       INT       NULL,
    IND_PROCESS_DAYS    INT       NULL,
    IND_STEP_DATE       DATE      NULL,
    IND_STEP_STATUS     INT       NULL,
    IND_NEXT_STEP       INT       NULL,
    IND_RESPONSE        INT       NULL,
    IND_LETTER_ID       CHAR (50) NULL,
    IND_LETTER_REV      INT       NULL,
    IND_TICKLE_DAYS     INT       NULL,
    IND_DOR_ID          INT       NULL,
    IND_AGENCY_ID       CHAR (9)  NULL,
    IND_USER_ID         INT       NULL,
    IND_SESSION_ID      INT       NULL,
    IND_LAST_UPD_DATE   DATE      NULL
);

CREATE TABLE CBC_PROCESS_OS_CACI (
    ISN_CBC_PROCESS_OS_CACI INT       NOT NULL,
    CACI_PER_ID             CHAR (10) NULL,
    CACI_STEP_DATE          DATE      NULL,
    CACI_LIC_TLR            CHAR (1)  NULL,
    CACI_STATE              CHAR (2)  NULL,
    CACI_REC_DATE           DATE      NULL,
    CACI_COUNTY             CHAR (20) NULL,
    CACI_STATUS             INT       NULL,
    CACI_STATUS_DATE        DATE      NULL,
    CACI_SEQ_NBR            INT       NULL
);

CREATE TABLE CBC_PROCESS_PER (
    ISN_CBC_PROCESS_PER INT       NOT NULL,
    PRO_PER_ID          CHAR (10) NULL,
    PRO_LIC_TLR         CHAR (1)  NULL,
    PRO_TAB_NBR         CHAR (2)  NULL,
    PRO_STEP_SEQ_NBR    INT       NULL,
    PRO_STEP_CRCS       INT       NULL,
    PRO_PROCESS_DAYS    INT       NULL,
    PRO_STEP_DATE       DATE      NULL,
    PRO_STEP_STATUS     INT       NULL,
    PRO_NEXT_STEP       INT       NULL,
    PRO_RESPONSE        INT       NULL,
    PRO_LETTER_ID       CHAR (50) NULL,
    PRO_LETTER_REV      INT       NULL,
    PRO_TICKLE_DAYS     INT       NULL,
    PRO_DOR_ID          INT       NULL,
    PRO_AGENCY_ID       CHAR (9)  NULL,
    PRO_USER_ID         INT       NULL,
    PRO_SESSION_ID      INT       NULL,
    PRO_LAST_UPD_DATE   DATE      NULL,
    PRO_STEP_TLR_STATUS CHAR (4)  NULL
);

CREATE TABLE CBC_SSN (
    ISN_CBC_SSN    INT       NOT NULL,
    SSN_PER_ID     CHAR (10) NULL,
    SSN_PRIMARY    CHAR (1)  NULL,
    SSN_NBR        INT       NULL,
    SSN_PER_STATUS CHAR (1)  NULL
);

CREATE TABLE CBC_STATS_FILE (
    ISN_CBC_STATS_FILE INT      NOT NULL,
    ST_REC_TYPE        CHAR (2) NULL,
    ST_TRANS_DATE      DATE     NULL,
    ST_CA_CLEAR        INT      NULL,
    ST_CA_REC          INT      NULL,
    ST_DOJ_CLEAR       INT      NULL,
    ST_DOJ_RAP         INT      NULL,
    ST_FBI_CLEAR       INT      NULL,
    ST_FBI_RAP         INT      NULL,
    ST_CA_POSS         INT      NULL,
    ST_CA_UCL          INT      NULL,
    ST_CA_AMEND_CLEAR  INT      NULL,
    ST_CA_AMEND_POSS   INT      NULL,
    ST_CA_BACK_POSS    INT      NULL,
    ST_CA_AMEND_MULT   INT      NULL,
    ST_DOJ_DELAY       INT      NULL,
    ST_DOJ_NAME_CLEAR  INT      NULL,
    ST_DOJ_FPC_REJECT  INT      NULL,
    ST_FBI_DELAY       INT      NULL,
    ST_FBI_NAME_CLEAR  INT      NULL,
    ST_FBI_FPC_REJECT  INT      NULL,
    ST_DOJ_SUBRAP      INT      NULL,
    ST_DOJ_SUBDISPO    INT      NULL
);

CREATE TABLE CBC_TABLE_FILE (
    ISN_CBC_TABLE_FILE         INT       NOT NULL,
    TBL_PER_STATUS             CHAR (1)  NULL,
    TBL_PER_STATUS_DESC        CHAR (50) NULL,
    TBL_CRCS                   INT       NULL,
    TBL_CRCS_DESC              CHAR (50) NULL,
    TBL_TLR_STATUS             CHAR (4)  NULL,
    TBL_TLR_STATUS_DESC        CHAR (50) NULL,
    TBL_ACTION_STATUS          INT       NULL,
    TBL_ACTION_STATUS_DESC     CHAR (50) NULL,
    TBL_STEP_STATUS            INT       NULL,
    TBL_STEP_STATUS_DESC       CHAR (50) NULL,
    TBL_STEP_STAT_ALLOW_TICKLE CHAR (1)  NULL,
    TBL_STEP_STAT_TICKLE_DAYS  INT       NULL,
    TBL_RESPONSE               INT       NULL,
    TBL_RESPONSE_DESC          CHAR (50) NULL,
    TBL_USER_ID                INT       NULL,
    TBL_USER_LOGIN_NAME        CHAR (25) NULL,
    TBL_IO_NBR                 INT       NULL,
    TBL_IO_DESC                CHAR (20) NULL,
    TBL_REG_STATUS             INT       NULL,
    TBL_REG_STATUS_DESC        CHAR (10) NULL
);

CREATE TABLE CBC_TLR_APPL (
    ISN_CBC_TLR_APPL     INT       NOT NULL,
    APL_PER_ID           CHAR (10) NULL,
    APL_TLR_TYPE         CHAR (15) NULL,
    APL_TLR_ID           CHAR (7)  NULL,
    APL_SELF_DISC        CHAR (1)  NULL,
    APL_APP_SIGNED       CHAR (1)  NULL,
    APL_APP_DATE         DATE      NULL,
    APL_LIVESCAN         CHAR (1)  NULL,
    APL_FPC_SUBMIT       CHAR (1)  NULL,
    APL_FPC_SIGNED       CHAR (1)  NULL,
    APL_PHOTO_ID         CHAR (1)  NULL,
    APL_RR_DOB           CHAR (1)  NULL,
    APL_RR_ID            CHAR (1)  NULL,
    APL_RR_PGM           CHAR (1)  NULL,
    APL_RR_FPC           CHAR (1)  NULL,
    APL_RR_FPC_SIGNED    CHAR (1)  NULL,
    APL_RR_APP_DATE      CHAR (1)  NULL,
    APL_RR_APP_SIGNED    CHAR (1)  NULL,
    APL_RR_APP_MISC      CHAR (1)  NULL,
    APL_CREATE_DATE      DATE      NULL,
    APL_CREATE_USER_ID   INT       NULL,
    APL_LAST_UPD_DATE    DATE      NULL,
    APL_LAST_UPD_USER_ID INT       NULL,
    APL_LUD_TIME         INT       NULL,
    APL_PGM_LUD_TIME     INT       NULL,
    APL_CN_LUD_TIME      INT       NULL,
    APL_PGM8_LUD_TIME    INT       NULL,
    APL_TLR_STATUS       CHAR (4)  NULL,
    APL_TLR_CRCS         INT       NULL,
    APL_CLEARED_DATE     DATE      NULL,
    APL_CLOSED_DATE      DATE      NULL,
    APL_CRCS_CA          INT       NULL,
    APL_CRCS_DOJ         INT       NULL,
    APL_CRCS_FBI         INT       NULL,
    APL_STEP_STATUS_CA   INT       NULL,
    APL_STEP_STATUS_DOJ  INT       NULL,
    APL_STEP_STATUS_FBI  INT       NULL,
    APL_CLEAR_LTR        CHAR (1)  NULL
);

CREATE TABLE CBC_TLR_CASENBR (
    ISN_CBC_TLR_CASENBR INT       NOT NULL,
    CN_TLR_ID           CHAR (7)  NULL,
    CN_PROG_ID          INT       NULL,
    CN_BOX_ID           CHAR (3)  NULL,
    CN_CASE_NBR         CHAR (30) NULL,
    CN_INPUT_DATE       DATE      NULL
);

CREATE TABLE CBC_TLR_PGM_BOX8 (
    ISN_CBC_TLR_PGM_BOX8 INT       NOT NULL,
    PGM8_TLR_ID          CHAR (7)  NULL,
    PGM8_PROG_ID         INT       NULL,
    PGM8_AGENCY_NBR      CHAR (15) NULL,
    PGM8_NAME            CHAR (30) NULL,
    PGM8_ADDRESS1        CHAR (25) NULL,
    PGM8_ADDRESS2        CHAR (25) NULL,
    PGM8_CITY            CHAR (25) NULL,
    PGM8_STATE           CHAR (2)  NULL,
    PGM8_ZIP             CHAR (5)  NULL
);

CREATE TABLE CBC_TLR_PROGRAM (
    ISN_CBC_TLR_PROGRAM INT       NOT NULL,
    PGM_TLR_ID          CHAR (7)  NULL,
    PGM_PROG_ID         INT       NULL,
    PGM_CWD_COUNTY_CODE CHAR (8)  NULL,
    PGM_CWD_OPTION      INT       NULL,
    PGM_CWD_WORKER_NAME CHAR (30) NULL,
    PGM_CWD_WORK_PHONE  CHAR (15) NULL,
    PGM_CWD_SIGNED      CHAR (1)  NULL,
    PGM_CWD_DATE        DATE      NULL,
    PGM_CCR_COUNTY_CODE CHAR (2)  NULL,
    PGM_CCR_OPTION      INT       NULL,
    PGM_CCR_RR_CODE     CHAR (6)  NULL,
    PGM_CCR_APP_CODE    CHAR (8)  NULL,
    PGM_CCR_RR_PROGRAM  CHAR (20) NULL,
    PGM_CCR_RR_NAME     CHAR (30) NULL,
    PGM_CCR_RR_PHONE    CHAR (15) NULL,
    PGM_CCR_SIGNED      CHAR (1)  NULL,
    PGM_CCR_DATE        DATE      NULL,
    PGM_AGENCY_NBR      CHAR (15) NULL,
    PGM_ACTIVE_DATE     DATE      NULL,
    PGM_TLR_TYPE        CHAR (15) NULL
);

CREATE TABLE CBC_UTRK_FIELDS (
    ISN_CBC_UTRK_FIELDS INT       NOT NULL,
    UTF_BYTE_POS        INT       NULL,
    UTF_FIELD_NAME      CHAR (50) NULL
);

CREATE TABLE LIS_AA_FILE (
    ISN_LIS_AA_FILE   INT       NOT NULL,
    AA_PER_ID         CHAR (10) NULL,
    AA_LEGAL_CASE_NBR CHAR (13) NULL,
    AA_PERSONNEL_TYPE CHAR (1)  NULL,
    AA_STATUS         INT       NULL,
    AA_LAST_UPD_DATE  DATE      NULL,
    AA_FAC_NAME       CHAR (50) NULL,
    AA_FAC_NBR        INT       NULL,
    AA_DO_NBR         INT       NULL,
    AA_ACTION_CODE    CHAR (1)  NULL,
    AA_CLOSED_CODE    INT       NULL,
    AA_REFER_DATE     DATE      NULL,
    AA_CLOSED_DATE    DATE      NULL
);

CREATE TABLE LIS_DO_FILE (
    ISN_LIS_DO_FILE INT       NOT NULL,
    DO_NBR          INT       NOT NULL,
    DO_NAME         CHAR (20) NULL,
    DO_STREET_ADDR  CHAR (30) NULL,
    DO_CITY         CHAR (20) NULL,
    DO_STATE        CHAR (2)  NULL,
    DO_ZIP_CODE     CHAR (9)  NULL,
    DO_PHONE_NBR    CHAR (10) NULL,
    DO_CALSTARS_NBR INT       NULL,
    DO_UNIT_CODE    INT       NULL,
    DO_PRINT_DEST   CHAR (6)  NULL,
    DO_REGION_NBR   INT       NULL,
    DO_ACCESS_CODE  INT       NULL,
    DO_BLOCK_BEGIN  INT       NULL,
    DO_BLOCK_END    INT       NULL,
    DO_NEXT_FAC_NBR INT       NULL
);

CREATE TABLE LIS_EC_FILE (
    ISN_LIS_EC_FILE             INT          NOT NULL,
    EC_ACTION_CODE              CHAR (1)     NULL,
    EC_BEDS_ON_HOSP_WAIVER      INT          NULL,
    EC_BEDS_ON_BEDRIDDEN_WAIVER INT          NULL,
    EC_CONTACT_1                CHAR (26)    NULL,
    EC_CONTACT_2                CHAR (26)    NULL,
    EC_CONTACT_3                CHAR (26)    NULL,
    EC_PLAN_ON_REC              CHAR (1)     NULL,
    EC_FAC_CROSS_STRTS_1        CHAR (60)    NULL,
    EC_FAC_CROSS_STRTS_2        CHAR (60)    NULL,
    EC_FAC_NUMBER               INT          NULL,
    EC_GENDER_SERVED            CHAR (1)     NULL,
    EC_PHONE_1                  CHAR (10)    NULL,
    EC_PHONE_2                  CHAR (10)    NULL,
    EC_PHONE_3                  CHAR (10)    NULL,
    EC_LAST_CHANGED_BY          CHAR (26)    NULL,
    EC_LAST_UPD_DATE            DATE         NULL,
    EC_NBR_NONAMB_CLIENTS       INT          NULL,
    EC_OP_HRS_START             CHAR (4)     NULL,
    EC_OP_HRS_END               CHAR (4)     NULL,
    EC_RELO_DIRECTIONS          CHAR (150)   NULL,
    EC_RELO_CITY                CHAR (20)    NULL,
    EC_RELO_STATE               CHAR (2)     NULL,
    EC_RELO_STREET_ADDR         CHAR (30)    NULL,
    EC_RELO_ZIP                 CHAR (9)     NULL,
    EC_USER_ID                  CHAR (8)     NULL
);

CREATE TABLE LIS_FAC_FILE (
    ISN_LIS_FAC_FILE            INT        NOT NULL,
    FAC_NBR                     INT        NOT NULL,
    FAC_NAME                    CHAR (50)  NULL,
    FAC_DO_EVAL_CODE            CHAR (4)   NULL,
    FAC_DO_NBR                  INT        NULL,
    FAC_CO_NBR                  INT        NULL,
    FAC_FM_REGION_NBR           INT        NULL,
    FAC_CFIRS_ID_NBR            INT        NULL,
    FAC_STREET_SEARCH           CHAR (20)  NULL,
    FAC_TYPE                    INT        NULL,
    FAC_STATUS                  INT        NULL,
    FAC_RES_STREET_ADDR         CHAR (30)  NULL,
    FAC_RES_CITY                CHAR (20)  NULL,
    FAC_RES_STATE               CHAR (2)   NULL,
    FAC_RES_ZIP_CODE            CHAR (9)   NULL,
    FAC_MAIL_STREET_ADDR        CHAR (30)  NULL,
    FAC_MAIL_CITY               CHAR (20)  NULL,
    FAC_MAIL_STATE              CHAR (2)   NULL,
    FAC_MAIL_ZIP_CODE           CHAR (9)   NULL,
    FAC_LICENSEE_NAME           CHAR (50)  NULL,
    FAC_LICENSEE_TYPE           CHAR (1)   NULL,
    FAC_LIC_COMMENTS            CHAR (210) NULL,
    FAC_LIC_EFF_DATE            DATE       NULL,
    FAC_LIC_EXPIR_DATE          DATE       NULL,
    FAC_LIC_FIRST_DATE          DATE       NULL,
    FAC_LIC_LAST_CHANGE_DATE    DATE       NULL,
    FAC_LIC_MAIL_STREET_ADDR    CHAR (30)  NULL,
    FAC_LIC_MAIL_CITY           CHAR (20)  NULL,
    FAC_LIC_MAIL_STATE          CHAR (2)   NULL,
    FAC_LIC_MAIL_ZIP_CODE       CHAR (9)   NULL,
    FAC_ADMIN                   CHAR (26)  NULL,
    FAC_CAPACITY                INT        NULL,
    FAC_CLIENT_SERVED           INT        NULL,
    FAC_CLOSED_DATE             DATE       NULL,
    FAC_ORIG_APPL_REC_DATE      DATE       NULL,
    FAC_PHONE_NBR               CHAR (10)  NULL,
    FAC_ANNUAL_10_MO_DEFER_DATE DATE       NULL,
    FAC_ANNUAL_22_MO_DEFER_DATE DATE       NULL,
    FAC_ANNUAL_10_MO_VISIT_APPR CHAR (3)   NULL,
    FAC_ANNUAL_22_MO_VISIT_APPR CHAR (3)   NULL,
    FAC_ANNUAL_10_MO_VISIT_DATE DATE       NULL,
    FAC_ANNUAL_22_MO_VISIT_DATE DATE       NULL,
    FAC_LAST_VISIT_DATE         DATE       NULL,
    FAC_LAST_VISIT_REASON       INT        NULL,
    FAC_MID_YR_DEFER_DATE       DATE       NULL,
    FAC_MID_YR_VISIT_APPR       CHAR (3)   NULL,
    FAC_MID_YR_VISIT_DATE       DATE       NULL,
    FAC_POST_LIC_DEFER_DATE     DATE       NULL,
    FAC_POST_LIC_VISIT_APPR     CHAR (3)   NULL,
    FAC_POST_LIC_VISIT_DATE     DATE       NULL,
    FAC_RENEWAL_DEFER_DATE      DATE       NULL,
    FAC_RENEWAL_VISIT_APPR      CHAR (3)   NULL,
    FAC_RENEWAL_VISIT_DATE      DATE       NULL,
    FAC_LAST_FIRE_CLEAR_DATE    DATE       NULL,
    FAC_SFM_ID_NBR              CHAR (17)  NULL,
    FAC_AMB_1_17_NBR            INT        NULL,
    FAC_AMB_18_64_NBR           INT        NULL,
    FAC_AMB_65_PLUS_NBR         INT        NULL,
    FAC_NONAMB_1_17_NBR         INT        NULL,
    FAC_NONAMB_18_64_NBR        INT        NULL,
    FAC_NONAMB_65_PLUS_NBR      INT        NULL,
    FAC_UNLIC_ORIG_INPUT_DATE   DATE       NULL,
    FAC_CLOSED_PROCESS_DATE     DATE       NULL,
    FAC_CAP_INC_REC_DATE        DATE       NULL,
    FAC_REGION_NBR              INT        NULL,
    FAC_LAST_DEFER_VISIT_DATE   DATE       NULL,
    FAC_LAST_DEFER_VISIT_REASON INT        NULL,
    FAC_ANNUAL_VISIT_YEAR       INT        NULL,
    FAC_LAST_UPD_DATE           DATE       NULL,
    FAC_CAP_INC_CLOSED_DATE     DATE       NULL,
    FAC_ACTION_CODE             CHAR (1)   NULL,
    FAC_INC_CAP_EFF_DATE        DATE       NULL,
    FAC_LIC_COMMENTS_2          CHAR (210) NULL,
    FAC_CLIENT_SERVED_APPR_DATE DATE       NULL,
    FAC_LEGAL_ACTION_INDICATOR  CHAR (1)   NULL,
    FAC_AGG_STATUS              CHAR (1)   NULL,
    FAC_PRIMARY_NBR             INT        NULL,
    FAC_BILLING_DATE            DATE       NULL,
    FAC_DUAL_ID                 CHAR (1)   NULL,
    FAC_DUAL_NBR                CHAR (9)   NULL,
    FAC_FCRB_PRGM_NBR           CHAR (8)   NULL,
    FAC_GH_INDICATOR            CHAR (1)   NULL,
    FAC_COMPLAINT               CHAR (1)   NULL,
    FAC_DEFICIENCY              CHAR (1)   NULL,
    FAC_NBR_NEW                 INT        NULL,
    FAC_EMAIL_ADDRESS           CHAR (40)  NULL,
    FAC_PRE_LIC_VISIT_DATE      DATE       NULL,
    FAC_PLACEMENT_READY         CHAR (1)   NULL,
    FAC_PLACEMENT_DATE          DATE       NULL,
    FAC_REQUIRED_VISIT          CHAR (1)   NULL,
    FAC_PIN                     INT        NULL,
    FAC_OLD_FFA_NBR             INT        NULL,
    FAC_INACTIVE_NOTICE_DATE    DATE       NULL,
    FAC_INACTIVE_START_DATE     DATE       NULL,
    FAC_SOD_MATCH_DATE          DATE       NULL,
    FAC_ADDR_KEY                CHAR (19)  NULL,
    FAC_LOC_INDICATOR           CHAR (1)   NULL,
    FAC_TYPE999_CACI_INDICATOR  CHAR (1)   NULL,
    FAC_BILINGUAL               INT        NULL,
    FAC_REGION_DO               INT        NOT NULL,
    FAC_REGION_CO               INT        NOT NULL
);

CREATE TABLE LIS_FA_FILE (
    ISN_LIS_FA_FILE   INT       NOT NULL,
    FA_PER_ID         CHAR (10) NULL,
    FA_FAC_NBR        INT       NULL,
    FA_DO_NBR         INT       NULL,
    FA_START_DATE     DATE      NULL,
    FA_PERSONNEL_TYPE CHAR (1)  NULL,
    FA_END_DATE       DATE      NULL,
    FA_ACTION_CODE    CHAR (1)  NULL,
    FA_LAST_UPD_DATE  DATE      NULL,
    FA_FAC_TYPE       INT       NULL
);

CREATE TABLE LIS_LOC_FILE (
    ISN_LIS_LOC_FILE  INT       NOT NULL,
    LOC_FAC_NBR       INT       NULL,
    LOC_END_DATE      DATE      NULL,
    LOC_CO_NBR        INT       NULL,
    LOC_STREET_ADDR   CHAR (30) NULL,
    LOC_CITY          CHAR (20) NULL,
    LOC_STATE         CHAR (2)  NULL,
    LOC_ZIP_CODE      CHAR (9)  NULL,
    LOC_LAST_UPD_DATE DATE      NULL
);

CREATE TABLE LIS_SSV_FILE (
    ISN_LIS_SSV_FILE   INT       NOT NULL,
    SSV_PER_ID         CHAR (10) NULL,
    SSV_CATEGORY       INT       NULL,
    SSV_FAC_NAME       CHAR (50) NULL,
    SSV_FAC_NBR        INT       NULL,
    SSV_PERSONNEL_TYPE CHAR (1)  NULL,
    SSV_DATE           DATE      NULL,
    SSV_DO_NBR         INT       NULL,
    SSV_ACTION_CODE    CHAR (1)  NULL,
    SSV_LAST_UPD_DATE  DATE      NULL
);

CREATE TABLE LIS_TABLE_FILE (
    ISN_LIS_TABLE_FILE        INT       NOT NULL,
    TBL_AA_STATUS_CODE        INT       NULL,
    TBL_AA_STATUS_DESC        CHAR (70) NULL,
    TBL_ED_STATUS_CODE        INT       NULL,
    TBL_ED_STATUS_DESC        CHAR (70) NULL,
    TBL_FA_PER_TYPE_CODE      CHAR (1)  NULL,
    TBL_FA_PER_TYPE_DESC      CHAR (70) NULL,
    TBL_FAC_TYPE_CODE         INT       NULL,
    TBL_FAC_TYPE_DESC         CHAR (70) NULL,
    TBL_ACT_STATUS_CODE       INT       NULL,
    TBL_ACT_STATUS_DESC       CHAR (70) NULL,
    TBL_CARI_STATUS           INT       NULL,
    TBL_CARI_DESC             CHAR (70) NULL,
    TBL_CRCS_CODE             INT       NULL,
    TBL_CRCS_DESC             CHAR (70) NULL,
    TBL_SSV_CATEGORY_CODE     INT       NULL,
    TBL_SSV_CATEGORY_DESC     CHAR (70) NULL,
    TBL_LOG_ID                CHAR (8)  NULL,
    TBL_OLD_LOG_PASS          CHAR (8)  NULL,
    TBL_CO_NBR                INT       NULL,
    TBL_CO_DESC               CHAR (20) NULL,
    TBL_FAC_STATUS_CODE       INT       NULL,
    TBL_FAC_STATUS_DESC       CHAR (70) NULL,
    TBL_VISIT_REASON_CODE     INT       NULL,
    TBL_VISIT_REASON_DESC     CHAR (70) NULL,
    TBL_CLIENTS_SERVED_CODE   CHAR (3)  NULL,
    TBL_CLIENTS_SERVED_DESC   CHAR (20) NULL,
    TBL_FM_REGION_NBR         INT       NULL,
    TBL_FM_REGION_NAME        CHAR (50) NULL,
    TBL_FM_REGION_STREET_ADDR CHAR (30) NULL,
    TBL_FM_REGION_CITY        CHAR (20) NULL,
    TBL_FM_REGION_STATE       CHAR (2)  NULL,
    TBL_FM_REGION_ZIP_CODE    CHAR (9)  NULL,
    TBL_CO_COM_COPIES         INT       NULL,
    CFIRS_NBR                 INT       NULL,
    CFIRS_FM_NAME             CHAR (30) NULL,
    CFIRS_FM_STREET_ADDR      CHAR (30) NULL,
    CFIRS_FM_CITY             CHAR (20) NULL,
    CFIRS_FM_STATE            CHAR (2)  NULL,
    CFIRS_FM_ZIP_CODE         CHAR (9)  NULL,
    TBL_FAC_TYPE_ACRONYM      CHAR (8)  NULL,
    TBL_MONTH_CODE            INT       NULL,
    TBL_MONTH_DESC            CHAR (9)  NULL,
    TBL_LOG_PASS_DATE         INT       NULL,
    TBL_WV_CODE               INT       NULL,
    TBL_WV_DESC               CHAR (12) NULL,
    TBL_WV_SUM_DESC           CHAR (20) NULL,
    TBL_PHONE_AREA_CODE       CHAR (3)  NULL,
    TBL_REPORT_PASS           CHAR (8)  NULL,
    TBL_PER_ID                CHAR (10) NULL,
    TBL_SHUT_DOWN_TIME        INT       NULL,
    TBL_PER_ID_CONTROL        CHAR (1)  NULL,
    TBL_CWS_CODE              CHAR (1)  NULL,
    TBL_LAST_CWS_TRANS_DATE   DATE      NULL,
    TBL_PALS_LAST_TRANS_DATE  DATE      NULL,
    TBL_PALS_CODE             CHAR (1)  NULL,
    TBL_CLF_PAGE_CODE         CHAR (1)  NULL,
    TBL_FEE_TYPE_CODE         CHAR (1)  NULL,
    TBL_FEE_TYPE_DESC         CHAR (20) NULL,
    TBL_FAC_LICENSEE_CODE     CHAR (1)  NULL,
    TBL_FAC_LICENSEE_DESC     CHAR (25) NULL,
    TBL_AA_VIOLATION_DESC     CHAR (70) NULL,
    TBL_LCTS_ACTION_DESC      CHAR (70) NULL,
    TBL_FEE_PMT_PRTY          INT       NULL,
    TBL_FEE_TYPE_PRINT_DESC   CHAR (50) NULL,
    TBL_AA_FLAG               CHAR (1)  NULL,
    TBL_AA_FLAG_DESC          CHAR (15) NULL,
    TBL_FEE_TYPE_FPB          CHAR (1)  NULL,
    TBL_PONDERA_LAST_RUN_DATE DATE      NULL,
    TBL_AA_VIOLATION_CODE     CHAR (2)  NULL,
    TBL_LCTS_ACTION_CODE      CHAR (2)  NULL,
    TBL_FEE_PMT_TYPE          CHAR (1)  NULL,
    TBL_FEE_PMT_TYPE_DESC     CHAR (15) NULL,
    TBL_FEE_PRTY_TYPE         CHAR (3)  NOT NULL
);

CREATE TABLE LIS_TRAN_FILE (
    ISN_LIS_TRAN_FILE INT        NOT NULL,
    TRANS_CHECK_INFO  CHAR (25)  NULL,
    TRANS_DATE        INT        NULL,
    TRANS_OPERATOR    CHAR (8)   NULL,
    TRANS_DATA        CHAR (253) NULL,
    TRANS_DATA_2      CHAR (253) NULL,
    TRANS_DATA_3      CHAR (253) NULL,
    TRANS_DATA_4      CHAR (253) NULL,
    TRANS_TYPE        CHAR (3)   NOT NULL
);

