FROM ruby:latest

RUN gem install rails

RUN gem install puma

RUN apt-get update && apt-get install -y nodejs

RUN mkdir /var/www

# Clone the mock-api
# RUN git clone git@github.com:ca-cwds/cals-mock-api.git /var/www/cals-mock-api
RUN git clone https://github.com/ca-cwds/cals-mock-api.git /var/www/cals-mock-api

WORKDIR /var/www/cals-mock-api
RUN cd /var/www/cals-mock-api

RUN bundle install

ENV ELASTICSEARCH_HOST_URL=http://calses:9200
ENV DATABASE_USERNAME=pguser
ENV DATABASE_PASSWORD=
ENV DATABASE_NAME=pguser
ENV HOST_URL=calspostgres
ENV HOST_PORT=5432

# ONBUILD rake db:migrate RAILS_ENV=aws_dev

CMD rails server -e development -p 3001 -b 0.0.0.0
