FROM ruby:latest

RUN gem install rails

RUN gem install puma

RUN apt-get update

# Get latest nodejs PPA
RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -

# install nodejs and npm
RUN apt-get install -y nodejs

RUN mkdir /var/www; cd /var/www;

# clone CALS
RUN git clone -b aws_dev https://github.com/ca-cwds/CALS.git /var/www/cals

WORKDIR /var/www/cals
RUN cd /var/www/cals

RUN bundle install

#run node package installer
RUN npm install

# compile assets
RUN rails assets:precompile

ENV BASE_CALS_API_URL=http://devmockapi1.cs-cals.com:3001/v1

# run rails server
CMD rails server -e aws_dev -b 192.168.213.100

# CMD ["bundle", "exec", "rails", "server", "--binding", "192.168.213.100"]
# CMD ["/usr/local/bundle/bin/rails", "server", "--binding", "192.168.213.100", "-d"]

